spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clair_tax}
spring.datasource.username=khorzeyi
spring.datasource.password=Zeyi0821
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}
logging.level.org.hibernate.SQL=${HIBERNATE_SQL_LOG_LEVEL:INFO}
